config/routes.rb
Rails.application.routes.draw do
  
  root 'home#index'
  get '/articles' => 'articles#index'
  get '/articles/new' => 'articles#new'
  get '/articles/:id' => 'articles#show', as: 'article_show'
  post '/articles' => 'articles#create', as: 'article_create'
  get '/articles/edit/:id' => 'articles#edit', as: 'article_edit'
  put '/articles/:id' => 'articles#update', as: 'article_update'
  delete '/articles/:id' => 'articles#destroy', as: 'article_destroy'
  
  # get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    validates :name, presence: true, uniqueness: true
    validates :body, presence: true, length: { minimum: 5 }
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    protect_from_forgery with: :null_session
    
    def index
        @articles = Article.all
    end

    def new
        @article = Article.new
    end

    def show
        @article = Article.find(params[:id]) 
    end

    def create
        @article = Article.new(article_params)

        if @article.save
            redirect_to articles_path
        else
            render :new
        end
    end

    def edit
        @article = Article.find(params[:id])
    end

    def update
        @article = Article.find(params[:id])

        if @article.update(article_params)
            redirect_to articles_path
        else
            render :edit
        end
    end

    def destroy
        @article = Article.find(params[:id])
        if @article.delete
            redirect_to articles_path
        else
            render :edit
        end
    end

    private
    def article_params
        params.require(:article).permit(:name, :body)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/articles/edit.html.erb
<div class="edit-main">
    <div class="form-container">
        <%= form_with scope: :article, url: article_update_path(@article.id), method: "put",local: true, data: { turbo_confirm: 'Are you sure ?' } do |f| %>

                <%
=begin%>
 <p>
                    <% if @article.errors.any? %>
                        <ul>
                            <% @article.errors.full_messages.each do |message| %>
                                <li><%= message %></li>
                            <% end %>
                        </ul>
                    <% end %>
                </p> 

<%
=end%>
                <div class="form-header">
                    <h1>Modify article:</h1>
                </div><br />

                <div class="form-article">
                    <p>
                        <%= f.label :title %><br />
                        <%= f.text_field :name %>
                    </p><br />
                    
                    <p>
                        <%= f.label :content %><br />
                        <%= f.rich_text_area :body %>
                    </p><br />
                </div>
                
                <div class="form-footer">
                    <p>
                        <%= f.submit 'Update' %>
                        <%= f.button "Delete", formmethod: :delete %>
                    </p><br />
                </div>

            <% end %>
    </div><br />
        
                <p>
                    <%= link_to 'Back to articles', articles_path %>
                </p><br />
</div>

app/views/articles/index.html.erb
<div class="article_index_main">
    <br />
    <div>
        <h1>Blog Article</h1>
    </div>
    <br />
    <div>
        <table>
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Title</th>
                    <th colspan="2">Action</th>
                </tr>

            </thead>
            <tbody>
                <% @articles.each do |article|%>
                    <tr>
                        <td><%= article.id %></td>
                        <td><%= article.name %></td>
                        <td><%= link_to 'view', article_show_path(article.id) %></td>
                        <td><%= link_to 'edit', article_edit_path(article.id) %></td>
                        
                    </tr>
                <% end %>
            </tbody>
        </table>
        <br /> <br />
    </div>
    <div>
        <%= link_to 'New article', articles_new_path, class: 'new_article' %>
        
    </div>
</div>

app/views/articles/new.html.erb
<div class="new-main">
    <div class="form-container">
        <%= form_with scope: :article, url: article_create_path , local: true, data: {turbo: false} do |f| %>
            <div class="form-header">
                <h1>New article:</h1>
            </div><br />
                <div>
                    <p>
                        <% if @article.errors.any? %>
                                <ul classs="validation-message">
                                    <% @article.errors.full_messages.each do |message| %>
                                        <li style="list-style-type:none; color:#ff2e46;"><%= message %></li>
                                    <% end %>
                                </ul>
                        <% end %>
                    </p><br />
                </div>
            <div class="form-article">
                <p>
                <%= f.label :title %><br />
                <%= f.text_field :name %>
                </p><br />
            
                <p>
                    <%= f.label :content %><br />
                    <%= f.rich_text_area :body, placeholder: "Any description?" %>
                </p><br />
            </div>
            
            <div class="form-footer">
                <p>
                    <%= f.submit 'Add article'%>&nbsp;&nbsp;&nbsp;&nbsp;<%= link_to 'Back to articles', articles_path %>
                </p><br />
            </div>
    
    <% end %>
    </div>
</div>

app/views/articles/show.html.erb
<div class="show-main">
    <div class="container">
        <div class="title">
            <h2><%= @article.name %></h2>
        </div>
        <div class="body">
            <%= @article.body %>
        </div>
    </div><br /><br />
    <div>
        <%= link_to 'Back to article list', articles_path %>
    </div>
</div>

app/views/home/index.html.erb
<div>
    Hello World!
</div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>